macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:  
  env:
    MIRRORD_AGENT_RUST_LOG: "warn,mirrord=debug"
  script_install_rust:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain nightly -y
    - . $HOME/.cargo/env
    - rustup default nightly
    - rustup component add rustfmt
  script_install_dependencies:
    - brew install node
    - npm install express
    - brew install python
    - pip3 install flask   